services:
  bot:
    build: .
    container_name: telegram_helper
    restart: always  # Перезапускать автоматически, если упадет
    env_file:
      - .env        # Читать настройки прямо из вашего .env файла
    ports:
      - "8000:8000" # Пробросить порт наружу (Внешний:Внутренний)
    volumes:
      # Пробрасываем папку с логами, чтобы они сохранялись на сервере, а не исчезали с контейнером
      - ./logs:/app/logs
